// Real browser + Neon smoke. No mocked API or approvals.
import {chromium} from '../frontend/node_modules/playwright-core/index.mjs';
import {mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
assert.ok(process.env.DEMO_EMAIL && process.env.DEMO_PASSWORD);
const origin=process.env.APP_ORIGIN || 'http://localhost:5173';
const browser=await chromium.launch({channel:'msedge',headless:true});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 page.setDefaultTimeout(60000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin);
 const row=page.getByRole('row').filter({hasText:'ACT-24-SPOOL-01'});await row.waitFor();
 assert.equal(await row.count(),1);
 await mkdir('docs/screenshots',{recursive:true});
 await page.screenshot({path:'docs/screenshots/cloud-dashboard.png',fullPage:true});
 const projectId=page.url().split('/projects/')[1].split('/')[0];
 await page.getByRole('button',{name:'Civil',exact:true}).click();
 assert.equal(await row.count(),0);
 await page.getByRole('row').filter({hasText:'ACT-CIV-24-01'}).waitFor();
 await page.getByRole('button',{name:'All',exact:true}).click();
 await page.getByRole('button',{name:'Gantt',exact:true}).click();
 await page.locator('.gantt-row').first().waitFor();
 await page.getByRole('button',{name:'Table',exact:true}).click();
 const exported=await page.request.get(`${origin}/api/projects/${projectId}/exports?format=json`);
 assert.equal(exported.status(),200);assert.equal((await exported.json()).schema_version,'plan2field-enterprise-v1');
 const csv=await page.request.get(`${origin}/api/projects/${projectId}/exports?format=csv`);
 assert.match(await csv.text(),/ActualStartDate,ActualFinishDate,PhysicalPercentComplete/);
 await page.getByRole('link',{name:'Submit report',exact:true}).click();
 await page.getByLabel('Discipline',{exact:true}).waitFor();
 assert.equal(await page.getByLabel('Discipline',{exact:true}).locator('option').count(),7);
 await page.getByRole('link',{name:'Historical knowledge',exact:true}).click();
 await page.getByRole('heading',{name:'Institutional Memory',exact:true}).waitFor();
 assert.equal(await page.locator('a[href*="undefined"]').count(),0);
 await page.getByLabel('Include synthetic demo comparables').check();
 await page.locator('.history-record').first().waitFor();
 await page.getByRole('link',{name:'Overview',exact:true}).click();await row.waitFor();
 await page.goto(origin+'/projects/undefined/review');await row.waitFor();
 await page.getByRole('link',{name:'Review queue',exact:true}).click();
 await page.getByRole('heading',{name:/observation/}).first().waitFor();
 await page.getByText('Planner Review Required',{exact:true}).waitFor();
 await page.screenshot({path:'docs/screenshots/cloud-review.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('link',{name:'Overview',exact:true}).click();await row.waitFor();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:'docs/screenshots/cloud-mobile.png',fullPage:true});
 const ready=await page.request.get(origin+'/api/health/ready');
 assert.equal(ready.status(),200);assert.deepEqual(await ready.json(),{database:true,models:true,worker:true});
 assert.deepEqual(errors,[]);
 console.log('PASS: real login, seeded schedule, discipline filters, Gantt, six-discipline ingestion, history navigation, invalid-project recovery, reviewer CTA, enterprise downloads, mobile layout and readiness. No approvals performed.');
} finally {await browser.close();}
