import test from 'node:test';import assert from 'node:assert/strict';
import {calculateProgress} from '../../src/services/progressService.js';
import {eventSchema} from '../../src/schemas/event.js';
import {variance} from '../../src/services/varianceService.js';
const a={line_number:'24',activity_type:'ERECTION',discipline:'PIPING',area:'NORTH',accepted_quantity:'0',physical_percent_complete:'0',planned_total_quantity:'10',quantity_unit:'spool',measurement_method:'EQUAL_COMPONENTS',actual_start:null,actual_finish:null};
const event=eventSchema.parse({event_type:'PROGRESS',event_date:'2026-09-15',action:'ERECTION',line_number:'24',area:'NORTH',discipline:'PIPING',quantity:3,unit:'spool',quantity_mode:'COMPONENT_SET',component_ids:['S01','S02','S03']});
const components=Array.from({length:10},(_,i)=>({external_id:`S${String(i+1).padStart(2,'0')}`,weight:1}));
test('three distinct components of ten is 30%, without inferred dates',()=>{const r=calculateProgress(a,event,components,[]);assert.equal(r.accepted_quantity,'3');assert.equal(r.physical_percent_complete,'30');assert.equal(r.actual_start,null);assert.equal(r.actual_finish,null);});
test('repeated component reports do not add quantity',()=>{const r=calculateProgress({...a,accepted_quantity:'3',physical_percent_complete:'30'},event,components,['S01','S02','S03']);assert.equal(r.accepted_quantity,'3');});
test('unequal component weights determine physical percentage',()=>{const c=[{external_id:'S01',weight:1},{external_id:'S02',weight:3}];const r=calculateProgress({...a,planned_total_quantity:'2',measurement_method:'WEIGHTED_COMPONENTS'},{...event,component_ids:['S02']},c,[]);assert.equal(r.physical_percent_complete,'75');});
test('cumulative and incremental quantities differ',()=>{const base={...a,measurement_method:'QUANTITY',accepted_quantity:'3',physical_percent_complete:'30'};assert.equal(calculateProgress(base,{...event,quantity_mode:'CUMULATIVE',component_ids:[]},[],[]).accepted_quantity,'3');assert.equal(calculateProgress(base,{...event,quantity_mode:'INCREMENTAL',component_ids:[]},[],[]).accepted_quantity,'6');});
test('invalid scope, quantity and future evidence rejected',()=>{assert.throws(()=>calculateProgress(a,{...event,line_number:'42'},components,[]));assert.throws(()=>calculateProgress(a,{...event,event_type:'PLAN'},components,[]));assert.throws(()=>calculateProgress(a,{...event,negated:true},components,[]));assert.throws(()=>calculateProgress(a,{...event,component_ids:['S99']},components,[]));});
test('date-only variance has correct sign and null semantics',()=>{assert.equal(variance('2026-09-12','2026-09-10'),2);assert.equal(variance('2026-09-09','2026-09-10'),-1);assert.equal(variance(null,'2026-09-10'),null);});
test('correction replaces component projection while requiring event reference',()=>{assert.throws(()=>calculateProgress(a,{...event,event_type:'CORRECTION'},components,['S01','S02','S03']));const r=calculateProgress(a,{...event,event_type:'CORRECTION',correction_of_event_id:'00000000-0000-4000-8000-000000000001',component_ids:['S01','S02']},components,['S01','S02','S03']);assert.equal(r.physical_percent_complete,'20');});
test('full physical completion alone leaves finish null',()=>{const r=calculateProgress(a,{...event,component_ids:components.map(c=>c.external_id)},components,[]);assert.equal(r.physical_percent_complete,'100');assert.equal(r.actual_finish,null);});
test('missing dates and incompatible units are rejected',()=>{assert.throws(()=>calculateProgress(a,{...event,event_date:null},components,[]));assert.throws(()=>calculateProgress(a,{...event,unit:'meter'},components,[]));});
test('lower cumulative observations require explicit correction',()=>{assert.throws(()=>calculateProgress({...a,accepted_quantity:'5',physical_percent_complete:'50',measurement_method:'QUANTITY'},{...event,quantity_mode:'CUMULATIVE',component_ids:[],quantity:3},[],[]));});
test('aggregate component mixing requires reconciliation',()=>{assert.throws(()=>calculateProgress({...a,accepted_quantity:'3',physical_percent_complete:'30'},event,components,[]));});
test('finish requires an approved start and complete scope',()=>{assert.throws(()=>calculateProgress(a,{...event,event_type:'FINISH'},components,[]));});
test('percentage normalizes only quantity-measured scope',()=>{
 const percent={...event,physical_percent:42.5,quantity:null,quantity_mode:null,component_ids:[]};
 const r=calculateProgress({...a,measurement_method:'QUANTITY'},percent,[],[]);
 assert.equal(r.accepted_quantity,'4.25');assert.equal(r.physical_percent_complete,'42.5');
 assert.throws(()=>calculateProgress(a,percent,components,[]),/component identities/);
 assert.throws(()=>calculateProgress({...a,measurement_method:'QUANTITY'},{...percent,quantity:3},[],[]),/either percentage/);
});
